site_name: Culture.pl 3.0 - Dokumentacja
pages:
  - 'Home': 'index.md'
  - 'Typy zawartości': 'Typy-zawartosci-migracja.md'
theme: readthedocs
site_author: "Ratio Web"
repo_url: https://github.com/culture-pl/culture-docs
